### ISSUE TITLE
Null Bytes in Auto_Open Lbl Results in Unprocessed Macros

### ISSUE THREAD

**Issue by michaelweber** [DissectMalware/XLMMacroDeobfuscator#9]
Example file @ [nullbyte-autoopen-bug.xls.zip](https://github.com/DissectMalware/XLMMacroDeobfuscator/files/4588967/nullbyte-autoopen-bug.xls.zip)

When a binary XLS file with the Auto_Open label has null bytes injected into its contents, the Auto_Open field will no longer be discover-able when processed at https://github.com/DissectMalware/XLMMacroDeobfuscator/blob/master/XLMMacroDeobfuscator/xls_wrapper.py#L134. This results in the tool never processing any of the macro cells in the document.

```
\Path\To\Python\Python37\Scripts>xlmdeobfuscator.exe -f nullbyte-autoopen-bug.xls -n
[Loading Cells]
time elapsed: 1.6042091846466064
```

The provided file is the same as the file in issue #8, but the Auto_Open Lbl record has been modified such that it contains null bytes.

**Comment by DissectMalware** [comment]
Currently, the code relies on Excel COM obj to get the defined names, it seems that the first inject null byte causes the string to be truncated.

![image](https://user-images.githubusercontent.com/9646319/81240772-53355980-8fd6-11ea-87cc-106a11a1d4c4.png)

No immediate fix for this bug. Seems correctly extracting the defined names requires parsing the xls file directly.

**Comment by DissectMalware** [comment]
XLSWrapper2, which relies on xlrd2 library, is added to the project that can be used instead of XLSWrapper to solve this issue.

To use XLSWrapper2 add --no-ms-excel switch.

**Comment by michaelweber** [comment]
I'm still having issues with the emulator identifying where to begin when the auto_open labels have been obfuscated. Cell extraction works fine with the -x setting, but even if I run with the newer setting, this still doesn't process - maybe xlrd's name_map is also impacted by the null byte injection?

```
Path\To\Python\Python37\Scripts>xlmdeobfuscator.exe --no-ms-excel -f obfuscated_autoopen_labels.xls
[Loading Cells]
time elapsed: 0.08974337577819824
```
[obfuscated_autoopen_labels.zip](https://github.com/DissectMalware/XLMMacroDeobfuscator/files/4605163/obfuscated_autoopen_labels.zip)

**Comment by DissectMalware** [comment]
I think I fixed the issue in XLSWrapper2

![image](https://user-images.githubusercontent.com/9646319/81508149-5b401280-92d0-11ea-8840-234ff05862ab.png)

Please check

**Comment by michaelweber** [comment]
Yeah, this looks fixed now. It does look like Excel has similar parsing issues where it will also ignore the BOM unicode character (\ufeff and \uffef) as well as some other unicode characters - I'm investigating to see if I can get a more generic list of characters which are ignored. Likely just dumping all characters that aren't printable will be fine, but this is definitely funky behavior on the part of Excel.

**Comment by michaelweber** [comment]
Created a test case with a large number of invalid unicode characters thrown into the name - once all unprintable characters are dropped before processing, this should be able to parse. The actual string (which is UTF16) is: "\u0000\ufefeA\uffffu\ufefft\ufffeo\uffef_\ufff0O\ufff1p\ufff6e\ufefdn\udddd"

[invalid-unicode-auto-open-label.zip](https://github.com/DissectMalware/XLMMacroDeobfuscator/files/4619439/invalid-unicode-auto-open-label.zip)

**Comment by DissectMalware** [comment]
Thank you Michael.

I think I fixed it in 

https://github.com/DissectMalware/XLMMacroDeobfuscator/commit/2e137f49c0aebe9a403ccbaa3853d0b8fb53969d

Please check it out

**Comment by michaelweber** [comment]
This one still isn't working for me, unfortunately. I did a fresh linux install (see #15) with the colBitStuffing example, and it looks like the obfuscated string is still not getting picked up / being detected as an Auto_Open. For example:

~~~
administrator@devmachine:/usr/local/lib/python3.5/dist-packages/XLMMacroDeobfuscator$ python3 deobfuscator.py -f colBitStuffing.xls -n -2
Excel is not present
[Loading Cells]
time elapsed: 0.396181583404541
~~~

The Auto_Open string here is "\u0000\ufefeA\uffffu\ufefft\ufffeo\uffef_\ufff0O\ufff1p\ufff6e\ufefdn\udddd" - which SHOULD fall into the current whitelist, but doesn't seem to be processed.

Additionally, you may want the tool to be overly aggressive with ignoring characters when considering an Auto_Open section. While the characters I use here are examples, they're not the complete set of characters which Excel will drop. For example, here's a sheet with "\u0000\uaeee\u9FFF\ucccc\ufefeA\uffffu\ufefft\ufffeo\uffef_\ufff0O\ufff1p\ufff6e\ufefdn\udddd" (\uaeee, \u9fff, and \ucccc are also prepended and ignored): 
[moreUnicodeFun.zip](https://github.com/DissectMalware/XLMMacroDeobfuscator/files/4640899/moreUnicodeFun.zip) - the "safe" bet here is probably to "drop" all characters outside of the normal printable ASCII range and see if the string Auto_Ope is still at the start. Yes, this will technically allow for false positives on auto_open fields, but the odds that someone is going to spell out Auto_Open in the middle of a different language's letter set while naming an Excel cell has got to be minimal.

**Comment by DissectMalware** [comment]
A few days ago, I realized the code for removing non-printable characters were deleted when I merged a pr. However, I reverted the removed code in https://github.com/DissectMalware/XLMMacroDeobfuscator/commit/823ebf04a1d17ca7a77bd02a0ce83787aae69d94. Please check once more

![image](https://user-images.githubusercontent.com/9646319/82636069-c55d8f00-9bcf-11ea-93a6-53da1ce5519e.png)
